name: Deployment

on:
  push:
    branches:
      - main

jobs:
  wait_for_tests:
    name: Wait for Tests
    runs-on: ubuntu-20.04
    steps:
     - name: Wait for Importer Test to finish
       uses: fountainhead/action-wait-for-check@v1.1.0
       with:
         token: ${{ secrets.GITHUB_TOKEN }}
         checkName: Importer Tests
         ref: ${{ github.event.pull_request.head.sha || github.sha }}

     - name: Wait for Exporter Test to finish
       uses: fountainhead/action-wait-for-check@v1.1.0
       with:
         token: ${{ secrets.GITHUB_TOKEN }}
         checkName: Exporter Tests
         ref: ${{ github.event.pull_request.head.sha || github.sha }}
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-20.04
    steps:
     - name: Checkout repository
       uses: actions/checkout@v2

     - name: Set up SSH
       run: |
         mkdir -p ~/.ssh
         chmod 700 ~/.ssh
         echo "${{ secrets.GH_DEPLOYMENT_KEY }}" > private_key
         chmod 600 private_key
         echo "${{ secrets.SERVER_IP }} ecdsa-sha2-nistp256 $(ssh-keyscan ${{ secrets.SERVER_IP }} 2>/dev/null)" >> ~/.ssh/known_hosts
         chmod 644 ~/.ssh/known_hosts

     - name: Deploy
       run: |
         ssh -i private_key ubuntu@${{ secrets.SERVER_IP }} "cd /home/ubuntu/fastapi-vizz-challenge && git pull && sudo systemctl restart fastapi-importer && sudo systemctl restart fastapi-exporter"
       shell: bash
